### ISSUE TITLE
U+11D8A GUNJALA GONDI VOWEL SIGN AA disappears contextually

### ISSUE THREAD

**Issue by dscorbett** [notofonts/gunjala-gondi#2]
### Font
NotoSansGunjalaGondi-Regular.otf

### Where the font came from, and when
Site: https://github.com/googlefonts/noto-fonts/blob/115d38430d957d38307457c036302b7bdbe0bbc4/phaseIII_only/unhinted/otf/NotoSansGunjalaGondi/NotoSansGunjalaGondi-Regular.otf
Date: 2020-04-12

### Font version
Version 1.001

### Issue
U+11D8A <i>ā</i> disappears before U+11D93 <i>ō</i> and U+11D94 <i>au</i>. These sequences should never occur: this bug hides typos.

### Character data
𑵬𑶊𑶓𑵬𑶊𑶔
U+11D6C GUNJALA GONDI LETTER YA
U+11D8A GUNJALA GONDI VOWEL SIGN AA
U+11D93 GUNJALA GONDI VOWEL SIGN OO
U+11D6C GUNJALA GONDI LETTER YA
U+11D8A GUNJALA GONDI VOWEL SIGN AA
U+11D94 GUNJALA GONDI VOWEL SIGN AU

### Screenshot
![𑵬𑶊𑶓𑵬𑶊𑶔](https://user-images.githubusercontent.com/1124347/79069204-73ede600-7c9a-11ea-982b-ea76e53c33df.png)

**Comment by simoncozens** [comment]
I don't think this is quite true. This graphic shows letter ya, ya+aa, ya+aa+oo. (𑵬 𑵬𑶊 𑵬𑶊𑶓)

![shape](https://github.com/notofonts/gunjala-gondi/assets/106728/16cd8eb9-da71-489b-af85-caa94fe2797e)

The aa matra is still present in the third sequence.

**Comment by dscorbett** [comment]
The strings <U+11D6C, U+11D8A, U+11D93> and <U+11D6C, U+11D93> both produce the glyph sequence <`YaMatraAa.GGondi`, `MatraEe.GGondi`>, and similar for U+11D94. The bug is that U+11D8A is suppressed. It should look like this:
![𑵬𑶊𑶓](https://github.com/notofonts/gunjala-gondi/assets/1124347/d676f8fd-647a-4ea4-b2cf-53aec6fa3af9)
That rendering looks wrong, which is appropriate because the input character sequence is wrong.

**Comment by simoncozens** [comment]
Oh, I see, the -OO is being converted into -AA -EE, and the way that this is applied assumes that there isn't already an -AA there. I get it now.
