### ISSUE TITLE
ZWJ behavior and Bha half form

### ISSUE THREAD

**Issue by vanisaac79** [notofonts/gunjala-gondi#5]
I just downloaded NotoSansGunjalaGondi-VariableFont_wght.ttf from fonts.google.com to create letter images for Wikimedia Commons and ran into two issues with the Gunjala Gondi font.

Issue #1: the font does not render as anticipated given the sequence &lt;Consonant> + &lt;Virama> + &lt;ZWJ>, where &lt;Consonant> is a character from U+11D6C .. U+11D89; &lt;Virama> is U+11D97; and &lt;ZWJ> is the Zero Width Joiner U+200D. In other Indic scripts, this will produce a bare half form of the preceding consonant character, but renders in Noto Sans Gunjala Gondi with an explicit Virama, the same as &lt;Consonant> + &lt;Virama> alone.

Issue #2: the half form of the character GUNJALA GONDI LETTER BHA, U+11D6F is missing a headline. This is in direct contradiction to the half form presented on page 7 of the accepted Unicode proposal document L2/15-235R (https://www.unicode.org/L2/L2015/15235r-gunjala-gondi.pdf). The headline is missing in all conjuncts of the form &lt;Bha> + &lt;Virama> + &lt;Consonant>.

These issues were present in OpenOffice Calc, under Apache OpenOffice 4.1.15, and remained in Inkscape 1.3.

I have developed a workaround for both of these issues, but believe that both issues should be rectified for general usage.

**Comment by simoncozens** [comment]
Thanks for reporting these! I've fixed them.
